server:
  port: 8080

spring:
  application:
    name: healthtagram

  profiles:
    active: dev

jwt:
  secret: 561ft65h1tr561t5456y15e6r1f5641hhfhgcvuig76r5d

#actuator 설정
management:
  server:
    port: 8181
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"