spring:
  data:
    mongodb:
      host: host.docker.internal
      port: 27017
      authentication-database: admin
      username: root
      password: root
      database: healthtagram

  redis:
    host: localhost
    port: 6379

  ############ MYSQL ##############
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://docker.host.internal:3306/healthtagram?rewriteBatchedStatements=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 2000
      #        format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

file:
  path: /tmp/healthtagramImage/

elastic:
  ip: host.docker.internal